title:               radiantkit
description:         'Radial Image Analysis Toolkir'

author:
  name:              Gabriele Girelli
  nickname:          GG
  url:               http://ggirelli.info
  email:             gabriele.girelli@scilifelab.se

version: 0.0.1.20210324.2
theme: jekyll-theme-minimal
google_analytics: "UA-99031010-8"
